module.exports = [
  { 'times': 'regular/times.svg' },
  { 'bars': 'regular/bars.svg' },
  { 'play': 'solid/play.svg' },
  { 'pause': 'solid/pause.svg' },
  { 'step-backward': 'solid/step-backward.svg' },
  { 'step-forward': 'solid/step-forward.svg' },
  { 'compact-disc': 'regular/compact-disc.svg' },
  { 'music': 'regular/music.svg' },
  { 'users': 'regular/users.svg' },
  { 'ellipsis-h': 'regular/ellipsis-h.svg' },
  { 'repeat': 'regular/repeat.svg' },
  { 'repeat-1': 'regular/repeat-1.svg' },
  { 'long-arrow-right': 'regular/long-arrow-right.svg' },
  { 'random': 'regular/random.svg' },
  { 'volume': 'regular/volume.svg' },
  { 'volume-up': 'regular/volume-up.svg' },
  { 'volume-down': 'regular/volume-down.svg' },
  { 'volume-mute': 'regular/volume-mute.svg' },
  { 'volume-slash': 'regular/volume-slash.svg' },
];
